spring:
  profiles:
    include: common
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

classroom:
  seatTime-period: 30